apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: leader-election
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: leader-election-nginx
    alpha.k8s.io/role-active: "true"
  type: ClusterIP